jobs:
  - name: gke-man-1
    type: manifest
    steps:
      - GET: gke-nginx-1
      - GET: image-opts-1
      - GET: trigger-gke-man-1

  - name: gke-beta-deploy-1
    type: gkeDeploy
    options:
      deployMethod: upgrade
    steps:
      - GET: gke-man-1
      - GET: gke-cluster-1
